name: "Release Go"

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Publish Go Package
    uses: ./.github/workflows/go-action.yml
    with:
      publish: true
    secrets: inherit
