name: Release API PHP SDK

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish PHP Package
    uses: ./.github/workflows/api-php-action.yml
    with:
      publish: true
    secrets: inherit
