name: Build API Typescript SDK sample

on:
  workflow_call:

jobs:
  build_and_publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm ci
      - name: Generate backend SDK
        run: ./api-typescript/build-sdk.ps1
        shell: pwsh
      - name: Build sample
        run: npm run build
        working-directory: ./api-typescript/samples
