name: Build Go sample

on:
  workflow_call:

jobs:
  build_and_publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Install NPM dependencies
        run: npm ci
      - name: Generate backend SDK
        run: ./backend/go.ps1
        shell: pwsh
      - name: Build sample
        run: go build -o go-sample
        working-directory: ./samples/go
