name: "Release PYPI"

on:
  workflow_dispatch:
  push:
    branches:
      - jp/publish-python

jobs:
  release:
    name: Publish PyPI Package
    uses: ./.github/workflows/pypi-action.yml
    with:
      publish: true
    secrets: inherit
