name: Release API Python SDK

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish PyPI Package
    uses: ./.github/workflows/api-python-action.yml
    with:
      publish: true
    secrets: inherit
