name: Build API Python SDK sample

on:
  workflow_call:

jobs:
  build_and_publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm ci
      - name: Build sample
        run: ./api-python/build-sample.ps1
        shell: pwsh
