name: "Release API Typescript SDK"

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish NPM Packages
    uses: ./.github/workflows/api-typescript-action.yml
    with:
      publish: true
    secrets: inherit
