name: Build and Publish Java Package

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm ci
      - name: Generate SDK
        run: ./backend/java.ps1
        shell: pwsh
      - name: Publish SDK
        if: inputs.publish == true
        run: ./publish/maven.ps1
        shell: pwsh
        env:
          MAVEN_GITHUB_USERNAME: ${{ secrets.GITHUB_MAVEN_USERNAME }}
          MAVEN_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
