name: Build and Publish NPM Packages

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm ci
      - name: Generate backend SDK
        run: ./backend/node.ps1
        shell: pwsh
      - name: Generate web SDK
        run: npm run build
        working-directory: ./client/web
      - name: Publish SDK
        if: inputs.publish == true
        run: ./publish/npm.ps1
        shell: pwsh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
