name: "PR Validation"

on:
  workflow_dispatch:
  pull_request:

jobs:
  nuget:
    name: Validate Nuget Package
    uses: ./.github/workflows/nuget-action.yml
    with:
      publish: false
    secrets: inherit
  go:
    name: Validate Go Package
    uses: ./.github/workflows/go-action.yml
    with:
      publish: false
    secrets: inherit
