name: "PR Validation"

on:
  workflow_dispatch:
  pull_request:

jobs:
  android:
    name: Validate Android Package
    uses: ./.github/workflows/android-action.yml
    with:
      publish: false
    secrets: inherit
  flutter:
    name: Validate Flutter Package
    uses: ./.github/workflows/flutter-action.yml
    with:
      publish: false
    secrets: inherit
  nuget:
    name: Validate Nuget Package
    uses: ./.github/workflows/nuget-action.yml
    with:
      publish: false
    secrets: inherit
  go:
    name: Validate Go Package
    uses: ./.github/workflows/go-action.yml
    with:
      publish: false
    secrets: inherit
  java:
    name: Validate Java Package
    uses: ./.github/workflows/java-action.yml
    with:
      publish: false
    secrets: inherit
  npm:
    name: Validate NPM Packages
    uses: ./.github/workflows/npm-action.yml
    with:
      publish: false
    secrets: inherit
  php:
    name: Validate PHP Packages
    uses: ./.github/workflows/php-action.yml
    with:
      publish: false
    secrets: inherit
  pypi:
    name: Validate PyPI Packages
    uses: ./.github/workflows/pypi-action.yml
    with:
      publish: false
    secrets: inherit
  rubygems:
    name: Validate Rubygems Packages
    uses: ./.github/workflows/rubygems-action.yml
    with:
      publish: false
    secrets: inherit
  samples-web-ui:
    name: Validate Web UI sample
    uses: ./.github/workflows/samples-web-ui.yml
  samples-node:
    name: Validate Node sample
    uses: ./.github/workflows/samples-node.yml
  samples-csharp:
    name: Validate C# sample
    uses: ./.github/workflows/samples-csharp.yml
  samples-go:
    name: Validate Go sample
    uses: ./.github/workflows/samples-go.yml
  samples-python:
    name: Validate Python sample
    uses: ./.github/workflows/samples-python.yml
  samples-python:
    name: Validate Java sample
    uses: ./.github/workflows/samples-java.yml
