name: "Renovate Bot"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1" # "At 09:00 on Monday."

jobs:
  renovate_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.8
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.MEWMBA_RENOVATE_TOKEN }}
