name: "Renovate Bot"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1-5" # "At 09:00 every day (Monday-Friday)."

jobs:
  renovate_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.2.10
        env:
          LOG_LEVEL: debug
        with:
          configurationFile: .github/renovate.json
          token: ${{ secrets.MEWMBA_RENOVATE_TOKEN }}
