name: "Release Rubygems"

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish Rubygems Package
    uses: ./.github/workflows/rubygems-action.yml
    with:
      publish: true
    secrets: inherit
