name: Build Web UI sample

on:
  workflow_call:

jobs:
  build_and_publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm ci
      - name: Build web sample
        run: npm run build
        working-directory: ./samples/web-ui
