name: Build Node sample

on:
  workflow_call:

jobs:
  build_and_publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NPM dependencies
        run: npm ci
      - name: Generate backend SDK
        run: ./backend/python.ps1
        shell: pwsh
      - name: Build sample
        run: python3 validate.py
        working-directory: ./samples/python
