name: "Release Android"

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish Android Package
    uses: ./.github/workflows/android-action.yml
    with:
      publish: true
    secrets: inherit
