name: Release UI Android SDK

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish Android Package
    uses: ./.github/workflows/ui-android-action.yml
    concurrency:
      group: git-release
    with:
      publish: true
    secrets: inherit
