name: Build and Publish UI Android SDK

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Build library
        run: |
          cd ./ui-android/sdk
          ./gradlew :library:build
      - name: Publish SDK
        if: inputs.publish == true
        run: ./ui-android/publish-sdk.ps1
        shell: pwsh
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
          SDK_REPOSITORY_PATH: ${{ github.repository }}
