name: Build and Publish Android Java Package

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install NPM dependencies
        run: npm ci
      - name: Publish SDK
        if: inputs.publish == true
        run: ./publish/android.ps1
        shell: pwsh
