name: Build and Publish UI Flutter SDK

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup credentials (todo investigate expiration)
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart
          cat <<EOF > $XDG_CONFIG_HOME/dart/pub-credentials.json
          {
            "accessToken":"${{ secrets.DART_PUB_OAUTH_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.DART_PUB_OAUTH_REFRESH_TOKEN }}",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1570721159348
          }
          EOF
      - name: Verify credentials
        run: cat $XDG_CONFIG_HOME/dart/pub-credentials.json
      - name: Run Flutter SDK Tests
        working-directory: ./ui-flutter/sdk
        run: flutter test
      - name: Build Sample Android App
        working-directory: ./ui-flutter/samples
        run: |
          sed -i 's/  trinsic_flutter_ui: \^[0-9.]*$/  trinsic_flutter_ui:/' pubspec.yaml
          sed -i 's|    # path: \.\./sdk/$|    path: ../sdk/|' pubspec.yaml
          cat pubspec.yaml
          flutter build apk
      - name: Publish SDK (dry run)
        working-directory: ./
        if: inputs.publish == false
        run: ./ui-flutter/publish-sdk.ps1 -dryRun
        shell: pwsh
      - name: Publish SDK
        working-directory: ./
        if: inputs.publish == true
        run: ./ui-flutter/publish-sdk.ps1
        shell: pwsh
