name: Build and Publish React Native library

on:
  workflow_call:
    inputs:
      publish:
        type: boolean
        required: false
        default: false
        description: "Publish the package, default is false"

jobs:
  release:
    name: Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install NPM dependencies
        run: npm ci
      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Install Dependencies
        run: xcodebuild -resolvePackageDependencies -project iOS.xcodeproj
        working-directory: ui-swift/samples/iOS
      - name: Generate ui react native SDK
        run: ./ui-react-native/build-sdk.ps1
        shell: pwsh
      - name: Publish ui react native SDK
        if: inputs.publish == true
        run: ./ui-react-native/publish-sdk.ps1
        shell: pwsh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

