name: Release UI React Native SDK

on:
  workflow_dispatch:

jobs:
  release:
    name: Publish
    uses: ./.github/workflows/ui-react-native-action.yml
    with:
      publish: true
    secrets: inherit
