name: Build and Publish UI Swift SDK

on:
  workflow_call:

jobs:
  build_and_publish:
    name: Build and Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: Publish SDK
        run: ./ui-swift/publish-sdk.ps1
        shell: pwsh
        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
          SDK_REPOSITORY_PATH: ${{ github.repository }}
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
